-- 初始化分类数据

INSERT INTO categories (name, slug, description, icon) VALUES
('开发工具', 'development', 'AI Agents for software development, code review, and debugging', '💻'),
('内容创作', 'content', 'AI Agents for writing, editing, and content generation', '✍️'),
('数据分析', 'data-analysis', 'AI Agents for data processing and analysis', '📊'),
('设计', 'design', 'AI Agents for graphic design and creative work', '🎨'),
('营销', 'marketing', 'AI Agents for marketing and SEO', '📈'),
('客服', 'customer-service', 'AI Agents for customer support', '💬'),
('教育', 'education', 'AI Agents for learning and teaching', '📚'),
('研究', 'research', 'AI Agents for research and information gathering', '🔬'),
('生产力', 'productivity', 'AI Agents for task management and productivity', '⚡'),
('其他', 'other', 'Other AI Agents', '🔧')
ON CONFLICT (slug) DO NOTHING;

-- Terminal UI 示例 Agents (10个覆盖不同类型)
-- 包含 entity_type, autonomy_level, metrics, status, rank, framework, geo_score, tags

INSERT INTO agents (
  name, slug, short_description, detailed_description, official_url, source,
  entity_type, autonomy_level, framework, metrics, status, rank, geo_score, tags,
  key_features, how_to_use, category_id
) VALUES
-- 1. SaaS + L5 + LangChain (Top Tier)
(
  'AutoDev Pro',
  'autodev-pro',
  'Fully autonomous code generation and deployment agent',
  'AutoDev Pro is a fully autonomous AI agent that handles the entire software development lifecycle. From requirements analysis to code generation, testing, and deployment - all without human intervention.',
  'https://autodev.pro',
  'official',
  'saas',
  'L5',
  'LangChain',
  '{"latency": 120, "uptime": 99.9, "cost": 0.025, "lastPing": "2024-01-15T10:00:00Z"}',
  'online',
  1,
  95,
  ARRAY['coding', 'automation', 'devops', 'enterprise'],
  ARRAY['Autonomous code generation', 'Auto-deployment', 'CI/CD integration', 'Multi-language support'],
  'Connect your GitHub repo and describe your requirements. AutoDev Pro handles the rest.',
  (SELECT id FROM categories WHERE slug = 'development')
),
-- 2. Repo + L4 + AutoGPT (Top Tier)
(
  'ResearchGPT',
  'research-gpt',
  'Autonomous research assistant with web browsing capabilities',
  'ResearchGPT is an open-source autonomous agent that conducts comprehensive research on any topic. It browses the web, synthesizes information, and produces detailed reports.',
  'https://github.com/research-gpt/research-gpt',
  'github',
  'repo',
  'L4',
  'AutoGPT',
  '{"stars": 15200, "forks": 2100, "lastCommit": "2024-01-14T08:30:00Z"}',
  'online',
  2,
  92,
  ARRAY['research', 'open-source', 'automation', 'free'],
  ARRAY['Web browsing', 'Multi-source synthesis', 'Citation generation', 'PDF export'],
  'Clone the repo, set your API keys, and run `python main.py --topic "your research topic"`',
  (SELECT id FROM categories WHERE slug = 'research')
),
-- 3. App + L4 + CrewAI (Top Tier)
(
  'DataCrew Desktop',
  'datacrew-desktop',
  'Multi-agent data analysis team in a desktop app',
  'DataCrew Desktop brings a team of specialized AI agents to your desktop. Analyst, Visualizer, and Reporter agents work together to transform raw data into actionable insights.',
  'https://datacrew.app',
  'official',
  'app',
  'L4',
  'CrewAI',
  '{"latency": 200, "uptime": 98.5, "cost": 0.015}',
  'online',
  3,
  88,
  ARRAY['data', 'visualization', 'reports', 'desktop'],
  ARRAY['Multi-agent collaboration', 'Auto-visualization', 'Report generation', 'Excel/CSV support'],
  'Download the app, import your data files, and let the crew analyze.',
  (SELECT id FROM categories WHERE slug = 'data-analysis')
),
-- 4. SaaS + L3 + LlamaIndex
(
  'DocuMind',
  'documind',
  'Intelligent document processing and Q&A agent',
  'DocuMind uses advanced RAG techniques to understand your documents and answer questions with precise citations. Perfect for legal, medical, and technical documentation.',
  'https://documind.ai',
  'official',
  'saas',
  'L3',
  'LlamaIndex',
  '{"latency": 180, "uptime": 99.5, "cost": 0.008, "lastPing": "2024-01-15T09:45:00Z"}',
  'online',
  4,
  82,
  ARRAY['documents', 'rag', 'enterprise', 'api'],
  ARRAY['Multi-format support', 'Citation tracking', 'Semantic search', 'API access'],
  'Upload documents via web interface or API. Ask questions in natural language.',
  (SELECT id FROM categories WHERE slug = 'productivity')
),
-- 5. Repo + L3 + BabyAGI
(
  'TaskForge',
  'taskforge',
  'Self-improving task management agent',
  'TaskForge is an open-source agent that breaks down complex goals into manageable tasks, executes them, and learns from the results to improve future performance.',
  'https://github.com/taskforge/taskforge',
  'github',
  'repo',
  'L3',
  'BabyAGI',
  '{"stars": 8500, "forks": 1200, "lastCommit": "2024-01-13T14:20:00Z"}',
  'online',
  5,
  78,
  ARRAY['tasks', 'automation', 'open-source', 'self-improving'],
  ARRAY['Goal decomposition', 'Task prioritization', 'Learning from feedback', 'Plugin system'],
  'Install via pip, configure your LLM provider, and set your first goal.',
  (SELECT id FROM categories WHERE slug = 'productivity')
),
-- 6. SaaS + L2 + Custom
(
  'WriteFlow',
  'writeflow',
  'AI writing assistant with style adaptation',
  'WriteFlow helps you write better content by adapting to your unique style. From blog posts to technical docs, it maintains your voice while improving clarity.',
  'https://writeflow.io',
  'official',
  'saas',
  'L2',
  NULL,
  '{"latency": 95, "uptime": 99.8, "cost": 0.005, "lastPing": "2024-01-15T10:15:00Z"}',
  'online',
  6,
  75,
  ARRAY['writing', 'content', 'style', 'free'],
  ARRAY['Style learning', 'Tone adjustment', 'Grammar check', 'SEO optimization'],
  'Sign up, paste your existing content to train your style profile, then start writing.',
  (SELECT id FROM categories WHERE slug = 'content')
),
-- 7. App + L2 + AutoGen
(
  'DesignMate',
  'designmate',
  'AI-powered design assistant for creatives',
  'DesignMate is a desktop companion that helps designers iterate faster. It suggests improvements, generates variations, and handles repetitive tasks.',
  'https://designmate.app',
  'official',
  'app',
  'L2',
  'AutoGen',
  '{"latency": 250, "uptime": 97.0}',
  'online',
  7,
  70,
  ARRAY['design', 'creative', 'desktop', 'image'],
  ARRAY['Design suggestions', 'Batch processing', 'Style transfer', 'Asset generation'],
  'Download for Mac/Windows, connect to Figma or Adobe, and start designing.',
  (SELECT id FROM categories WHERE slug = 'design')
),
-- 8. Repo + L2 + LangChain (Offline)
(
  'CodeReviewer',
  'codereviewer',
  'Automated code review agent for pull requests',
  'CodeReviewer automatically reviews your PRs, identifies bugs, suggests improvements, and ensures code quality standards are met.',
  'https://github.com/codereviewer/codereviewer',
  'github',
  'repo',
  'L2',
  'LangChain',
  '{"stars": 3200, "forks": 450, "lastCommit": "2024-01-10T16:00:00Z"}',
  'offline',
  8,
  65,
  ARRAY['coding', 'review', 'open-source', 'github'],
  ARRAY['PR integration', 'Bug detection', 'Style enforcement', 'Security scanning'],
  'Add as GitHub Action or run locally with `npx codereviewer review`',
  (SELECT id FROM categories WHERE slug = 'development')
),
-- 9. SaaS + L1 + Custom
(
  'TranslateBot',
  'translatebot',
  'Simple translation tool with context awareness',
  'TranslateBot provides accurate translations with context awareness. It understands technical jargon and maintains consistency across documents.',
  'https://translatebot.com',
  'official',
  'saas',
  'L1',
  NULL,
  '{"latency": 50, "uptime": 99.9, "cost": 0.002, "lastPing": "2024-01-15T10:30:00Z"}',
  'online',
  9,
  60,
  ARRAY['translation', 'api', 'enterprise'],
  ARRAY['100+ languages', 'Context memory', 'Glossary support', 'Batch translation'],
  'Use the web interface or integrate via REST API.',
  (SELECT id FROM categories WHERE slug = 'content')
),
-- 10. App + L1 + Custom (Maintenance)
(
  'VoiceNote',
  'voicenote',
  'Voice-to-text note taking with AI summaries',
  'VoiceNote captures your voice memos and converts them to organized notes with AI-generated summaries and action items.',
  'https://voicenote.app',
  'official',
  'app',
  'L1',
  NULL,
  '{"latency": 150, "uptime": 95.0}',
  'maintenance',
  10,
  55,
  ARRAY['voice', 'notes', 'mobile', 'transcription'],
  ARRAY['Real-time transcription', 'Auto-summarization', 'Action item extraction', 'Cloud sync'],
  'Download the mobile app, grant microphone access, and start recording.',
  (SELECT id FROM categories WHERE slug = 'productivity')
)
ON CONFLICT (slug) DO UPDATE SET
  entity_type = EXCLUDED.entity_type,
  autonomy_level = EXCLUDED.autonomy_level,
  framework = EXCLUDED.framework,
  metrics = EXCLUDED.metrics,
  status = EXCLUDED.status,
  rank = EXCLUDED.rank,
  geo_score = EXCLUDED.geo_score,
  tags = EXCLUDED.tags;
